// Code generated by "stringer -type=Resource"; DO NOT EDIT.

package images

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CalicoCNI-1]
	_ = x[CalicoController-2]
	_ = x[CalicoNode-3]
	_ = x[Flannel-4]
	_ = x[Cilium-5]
	_ = x[CiliumOperator-6]
	_ = x[HubbleRelay-7]
	_ = x[HubbleUI-8]
	_ = x[HubbleUIBackend-9]
	_ = x[HubbleProxy-10]
	_ = x[WeaveNetCNIKube-11]
	_ = x[WeaveNetCNINPC-12]
	_ = x[DNSNodeCache-13]
	_ = x[MachineController-14]
	_ = x[MetricsServer-15]
	_ = x[ClusterAutoscaler-16]
	_ = x[CSIAttacher-17]
	_ = x[CSINodeDriverRegistar-18]
	_ = x[CSIProvisioner-19]
	_ = x[CSISnapshotter-20]
	_ = x[CSIResizer-21]
	_ = x[CSILivenessProbe-22]
	_ = x[AzureCCM-23]
	_ = x[AzureCNM-24]
	_ = x[AzureFileCSI-25]
	_ = x[AzureFileCSIAttacher-26]
	_ = x[AzureFileCSILivenessProbe-27]
	_ = x[AzureFileCSINodeDriverRegistar-28]
	_ = x[AzureFileCSIProvisioner-29]
	_ = x[AzureFileCSIResizer-30]
	_ = x[AzureFileCSISnapshotter-31]
	_ = x[AzureFileCSISnapshotterController-32]
	_ = x[DigitalOceanCSI-33]
	_ = x[DigitalOceanCSIAutomount-34]
	_ = x[DigitalOceanCSIAttacher-35]
	_ = x[DigitalOceanCSINodeDriverRegistrar-36]
	_ = x[DigitalOceanCSIProvisioner-37]
	_ = x[DigitalOceanCSIResizer-38]
	_ = x[DigitalOceanCSISnapshotter-39]
	_ = x[DigitalOceanCSISnapshotController-40]
	_ = x[DigitaloceanCCM-41]
	_ = x[HetznerCCM-42]
	_ = x[HetznerCSI-43]
	_ = x[OpenstackCCM-44]
	_ = x[OpenstackCSI-45]
	_ = x[PacketCCM-46]
	_ = x[VsphereCCM-47]
	_ = x[VsphereCSIDriver-48]
	_ = x[VsphereCSISyncer-49]
}

const _Resource_name = "CalicoCNICalicoControllerCalicoNodeFlannelCiliumCiliumOperatorHubbleRelayHubbleUIHubbleUIBackendHubbleProxyWeaveNetCNIKubeWeaveNetCNINPCDNSNodeCacheMachineControllerMetricsServerClusterAutoscalerCSIAttacherCSINodeDriverRegistarCSIProvisionerCSISnapshotterCSIResizerCSILivenessProbeAzureCCMAzureCNMAzureFileCSIAzureFileCSIAttacherAzureFileCSILivenessProbeAzureFileCSINodeDriverRegistarAzureFileCSIProvisionerAzureFileCSIResizerAzureFileCSISnapshotterAzureFileCSISnapshotterControllerDigitalOceanCSIDigitalOceanCSIAutomountDigitalOceanCSIAttacherDigitalOceanCSINodeDriverRegistrarDigitalOceanCSIProvisionerDigitalOceanCSIResizerDigitalOceanCSISnapshotterDigitalOceanCSISnapshotControllerDigitaloceanCCMHetznerCCMHetznerCSIOpenstackCCMOpenstackCSIPacketCCMVsphereCCMVsphereCSIDriverVsphereCSISyncer"

var _Resource_index = [...]uint16{0, 9, 25, 35, 42, 48, 62, 73, 81, 96, 107, 122, 136, 148, 165, 178, 195, 206, 227, 241, 255, 265, 281, 289, 297, 309, 329, 354, 384, 407, 426, 449, 482, 497, 521, 544, 578, 604, 626, 652, 685, 700, 710, 720, 732, 744, 753, 763, 779, 795}

func (i Resource) String() string {
	i -= 1
	if i < 0 || i >= Resource(len(_Resource_index)-1) {
		return "Resource(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Resource_name[_Resource_index[i]:_Resource_index[i+1]]
}
